= OpenTelega =

OpenTelega — это сервер обмена файлами с открытым исходным кодом, написанный на веб-фреймворке _django_.
Простая структура сервера обеспечивает лёгкоcть написания собственных коммуникационных приложений, таких как чаты, мессенджеры, а также ботов к ним.

Взаимодействие с сервером осуществляется через команды, отправляемые на сервер по протоколу _HTTP_.
Поддерживается вывод в трёх форматах: _CSV_, _XML_, _JSON_ (по умолчанию), что позволяет разрабатывать на основе данного сервера свои приложения без использования стороннего программного обеспечения во всех современных средствах разработки ПО.

== Запуск сервера в тестовом окружении ==
. Клонируем репозиторий сервера:
+
[source, bash]
----
git clone https://github.com/opentelega/OpenTelega.git
----

. Переходим в папку сервера:
+
[source, bash]
----
cd OpenTelega
----

. Выполняем миграцию
+
[source, bash]
----
python manage.py makemigrations fileserver
python manage.py migrate
----

. Запускаем сервер
+
[source, bash]
----
python manage.py runserver
----

== Запуск тестирования ==
Для запуска тестов сервера необходимо набрать следующую команду:

[source, bash]
----
python manage.py test
----
